#ifndef DELEAGATES_TESTSUIT_H
#define DELEAGATES_TESTSUIT_H

#ifdef TESTSUIT_USING_CPP98
    #define DOCTEST_CONFIG_NO_VARIADIC_MACROS
    #define DOCTEST_CONFIG_NO_LONG_LONG
    #define DOCTEST_CONFIG_NO_STATIC_ASSERT
    #define DOCTEST_CONFIG_NO_NULLPTR
    #define DOCTEST_CONFIG_NO_RVALUE_REFERENCES
    #define DOCTEST_CONFIG_NO_DELETED_FUNCTIONS
    #define DOCTEST_CONFIG_NO_WINDOWS_SEH
    #define DOCTEST_CONFIG_NO_POSIX_SIGNALS
#endif

#include "./doctest.h"


#endif // DELEAGATES_TESTSUIT_H
