#ifndef DELEAGATES_TESTSUIT_H
#define DELEAGATES_TESTSUIT_H

#ifndef DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
    #define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
    #include "./doctest.h"
#endif // DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#endif // DELEAGATES_TESTSUIT_H