name: C/C++ CI

on:
  push:
    branches: [ tests ]
  pull_request:
    branches: [ tests ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: chmod +arwx ./build_tests.sh && ./build_tests.sh
    - name: run
      run: chmod +arwx ./run_tests.sh && ./run_tests.sh
